### ISSUE TITLE
Is it properly working?

### ISSUE THREAD

**Issue by Djensbeer** [ffd8/HEXPLODER#1]
I run the hexploder on windows. When i put a file in Hexploder, i dont get any good results yet. I try to change all the values and try to find another spot to hexplode it. Yet the only result im getting is that only half of the picture is not visible or there is only a line of the picture changed collors.

**Comment by ffd8** [comment]
Hey @Djensbeer – aha, that sounds like it's working, just not yet hitting a sweet spot of the file you're feeding it. It's also possible that Windows is censoring the glitched data (Apple started doing this in MacOS 10.10) – try using another image viewer to check the same files. I suggest starting with a very small jpg file, try the front section of the file, then test out moving the range further into the file.. there's a small silent [demo video here](https://www.youtube.com/watch?v=5I2s7N-gbg0). Getting good results will be needles within haystacks depending on the format you're using, which is what this tool tries to help you accidentally stumble upon. Smaller file + more compressed format will likely give quicker results.
